name: OpenCore little for GitBook deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setup Node.js Env
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          
      - name: Setup GitBook Env
        run:
          npm install gitbook-cli -g

      - name: Setup Calibre Env
        run:
          sudo apt-get update -y && sudo apt-get install calibre --fix-missing

      - name: Build
        run: |
          gitbook build . ./docs
          rm -rf ./docs/*.pdf
          gitbook pdf . ./docs/Python-100-Days.pdf
          
      - name: Commit
        run: |
          git add docs
          git config --local user.email "howiehye@qq.com"
          git config --local user.name "howiehye"
          git commit -m "Update by GitHub Actions" -a
      - name: Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
